# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'alexanderakulshin_dockerhub'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'alexanderakulshin_dockerhub'
        repository: 'alexanderakulshin/weatherapi'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: Docker@2
      inputs:
        containerRegistry: 'alexanderakulshin_dockerhub'
        repository: 'alexanderakulshin/weatherapi'
        command: 'push'
        tags: |
          $(tag)

